from django.urls import path
from . import views
from .views import get_cities, get_highschools
from .views import submit_individual_tour

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("guide_dashboard/", views.react_view, name="guide_dashboard"),
    path("advisor_dashboard/", views.react_view, name="advisor_dashboard"),
    path("coordinator_dashboard/", views.react_view, name="coordinator_dashboard"),
    path("director_dashboard/", views.react_view, name="director_dashboard"),
    path("promo_coordinator_dashboard/", views.react_view, name="promo_coordinator_dashboard"),
    path("guest_dashboard/", views.guest_dashboard, name="guest_dashboard"),
    path("apply_fair/", views.react_view, name="apply_fair"),
    path("apply_tour/", views.react_view, name="apply_tour"),
    path("apply_hs_tour/", views.react_view, name="apply_hs_tour"),
    path("apply_ind_tour/", views.react_view, name="apply_ind_tour"),
    path("give_feedback/", views.react_view, name="give_feedback"),
    path("contact_us/", views.react_view, name="contact_us"),  # Added this line
    path("fairs/", views.react_view, name="fairs"),
    path("guide_fairs/", views.react_view, name="guide_fairs"),
    path('cities/', get_cities, name='get_cities'),
    path('highschools/<str:city>/', get_highschools, name='get_highschools'),
    path("tour_application/", views.react_view, name="tour_application"),
    path("guide_list/", views.react_view, name="guide_list"),
    path("advisor_tours/", views.react_view, name="advisor_tours"),
    path("puantaj_page/", views.react_view, name="puantaj_page"),
    path("settings/", views.react_view, name="settings"),
    path('submit_tour/', views.submit_tour, name='submit_tour'),
    path('submit_individual_tour/', submit_individual_tour, name='submit_individual_tour'),
    path('submit_university_fair/', views.submit_university_fair, name='submit_university_fair'),
    path('coordinator_puantaj/', views.react_view, name='coordinator_puantaj'),
    path("responsible_advisors/", views.react_view, name="responsible_advisors"),
    path("coordinator_fair_applications/", views.react_view, name="coordinator_fair_applications"),
    path("accepted_tours/", views.react_view, name="accepted_tours"),
    path("coordinator_accepted_tours/", views.react_view, name="coordinator_accepted_tours"),    
    path("coordinator_view_guide_list/", views.react_view, name="coordinator_view_guide_list"),  
    path("coordinator_view_advisor_list/", views.react_view, name="coordinator_advisor_list"),  
    path("coordinator_view_feedback/", views.react_view, name="coordinator_view_feedback"),  
    path('highschool_tours/', views.get_highschool_tours, name='get_highschool_tours'),
    path('individual_tours/', views.get_individual_tours, name='get_individual_tours'),
    path('update_tour_status/', views.update_tour_status, name='update_tour_status'),
    path("coordinator_highschool_database/", views.react_view, name="coordinator_highschool_database"),  
    path("director_puantaj_page/", views.react_view, name="director_puantaj_page"), 
    path("director_database/", views.react_view, name="director_database"),
    path("director_fair_applications/", views.react_view, name="director_fair_applications"),
    path("director_accepted_tours/", views.react_view, name="director_accepted_tours/"),
    path("director_feedback/", views.react_view, name="director_feedback/"),
    path("promotional_coordinator_pauntaj/", views.react_view, name="promotional_coordinator_pauntaj"),
    path("promotional_coordinator_feedback/", views.react_view, name="promotional_coordinator_feedback"),
    path("promo_coordinator_tour_application/", views.react_view, name="promo_coordinator_tour_application"),
    path("promo_coordinator_fair_application/", views.react_view, name="promo_coordinator_fair_application"),
    path('accepted_highschool_tours/', views.get_accepted_highschool_tours, name='get_accepted_highschool_tours'),
    path('accepted_individual_tours/', views.get_accepted_individual_tours, name='get_accepted_individual_tours'),
    path('guides/', views.get_guides, name='get_guides'),
    path('get_fair_applications/', views.get_fair_applications, name='get_fair_applications'),
    path('get_accepted_fair_applications/', views.get_accepted_fair_applications, name='get_accepted_fair_applications'),
    path('update_fair_application_status/', views.update_fair_application_status, name='update_fair_application_status'),
    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),
    path('feedbacks/', views.get_feedbacks, name='get_feedbacks'),
    path('advisors/', views.advisor_list, name='advisor_list'),
    path('get_all_highschools/', views.get_all_highschools, name='get_all_highschools'),
    path('add_highschool/', views.add_highschool, name='add_highschool'),
    path('remove_guide/<int:guide_id>/', views.remove_guide, name='remove_guide'),
    path('add_guide/', views.add_guide, name='add_guide'),
]

