# Generated by Django 5.1.3 on 2024-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0003_highschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
