# Generated by Django 5.1.3 on 2024-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0004_alter_highschool_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='highschool',
            table='highschools',
        ),
    ]
