# Generated by Django 5.1.3 on 2024-12-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0005_alter_highschool_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor_name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('highschool', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
            ],
        ),
    ]
