# Generated by Django 5.1.3 on 2024-12-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0006_tour'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tour',
            table='highschooltours',
        ),
    ]
