# Generated by Django 5.1.3 on 2024-12-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0007_alter_tour_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='date',
            new_name='tour_date',
        ),
    ]
