# Generated by Django 5.1.3 on 2024-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0009_rename_tour_date_tour_date_tour_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('highschool', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('major_of_interest', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'individualtours',
            },
        ),
    ]
