# Generated by Django 5.1.3 on 2024-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs319projectapp', '0011_universityfair'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtour',
            name='guide_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide3_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
